# Imagem base
FROM node:14-alpine

# Diretório de trabalho
WORKDIR /app

# Copiar package.json e instalar dependências
COPY package.json package-lock.json ./
RUN npm install

# Copiar código-fonte
COPY . .

# Compilar o projeto
RUN npm run build

# Expor a porta 3000 e iniciar o servidor
EXPOSE 3000
CMD ["npm", "start"]
