name: Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checar o código no repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Logar no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 3: Build das imagens Docker
      - name: Build and Push Front-End Docker Image
        run: |
          docker build -t myapp-frontend ./frontend
          docker tag myapp-frontend ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest

      - name: Build and Push Back-End Docker Image
        run: |
          docker build -t myapp-backend ./backend
          docker tag myapp-backend ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest

      - name: Build and Push Database Docker Image
        run: |
          docker build -t myapp-database ./database
          docker tag myapp-database ${{ secrets.DOCKER_USERNAME }}/myapp-database:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-database:latest

      # Passo 4: Simulação de Deploy (Exemplo de Deploy para produção)
      - name: Deploy to Production
        run: |
          echo "Deploying to Production Environment"
          # Aqui você pode simular um deploy real (por exemplo, usando kubectl, SSH ou outros métodos)
